<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hospital [
    <!ELEMENT hospital (profesionales, pacientes)>
    <!ATTLIST hospital nombre CDATA #REQUIRED>

    <!--Así se hace un comentario en DTD. Como en HTML-->

    <!ELEMENT profesionales (auxiliares, cirujanos, enfermeros, doctores)>

    <!ELEMENT auxiliares (auxiliar*)>
    <!ELEMENT auxiliar EMPTY>
    <!ATTLIST auxiliar
        id CDATA #REQUIRED
        nombre CDATA #REQUIRED
        apellidos CDATA #REQUIRED
        seccion CDATA #REQUIRED
     >

    <!ELEMENT cirujanos (cirujano+)>
    <!ELEMENT cirujano (id, nombre, apellidos+, seccion)>

    <!ELEMENT enfermeros (enfermero*)>
    <!ELEMENT enfermero (nombre, apellidos+, seccion)>
    <!ATTLIST enfermero id CDATA #REQUIRED>

    <!ELEMENT doctores (doctor*)>
    <!ELEMENT doctor (apellidos+, seccion)>
    <!ATTLIST doctor
        id CDATA #REQUIRED
        nombre CDATA #IMPLIED
        licenciado CDATA #FIXED "Si">

    <!ELEMENT pacientes (paciente+)>
    <!ELEMENT paciente (fichaMedica)>
    <!ATTLIST paciente DNI CDATA #REQUIRED>


    <!ELEMENT id (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT seccion (#PCDATA)>
    <!ELEMENT fichaMedica (#PCDATA)>
]>

<hospital nombre="Hospital Central">
    <profesionales>
        <auxiliares>
            <auxiliar id="1" nombre="Pepito" apellidos="Sanchez Sanchez" seccion="Cardiología" />
        </auxiliares>
        <cirujanos>
            <cirujano>
                <id>2</id>
                <nombre>Juanito</nombre>
                <apellidos>Perez Sanchez</apellidos>
                <seccion>Traumatologia</seccion>
            </cirujano>
        </cirujanos>
        <enfermeros>
            <enfermero id="3">
                <nombre>Margarita</nombre>
                <apellidos>Lopez Gil</apellidos>
                <seccion>Cuidados Intensivos</seccion>
            </enfermero>
        </enfermeros>
        <doctores>
            <doctor id="4" nombre="Luisito" licenciado="Si">
                <apellidos>Martinez Martinez</apellidos>
                <seccion>Pediatria</seccion>
            </doctor>
        </doctores>
    </profesionales>
    <pacientes>
        <paciente DNI="12837128">
            <fichaMedica>Todo va perfecto, el paciente esta de 10.</fichaMedica>
        </paciente>
    </pacientes>
</hospital>